blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),
]

contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'

urlpatterns = [
 path('',views.messages,name="messages"),
 path('<int:message_id>/', views.messagedetail, name='messagedetail'),
 path('delete/<int:id>',views.delete_message,name="delete_message"),
 path('contactme/',views.contactme,name='contactme'),
]

majidfazel/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from portfolio.views import home,portfolio
from django.contrib.auth import views as authentication_views
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home,name='home'),
    path('portfolio',portfolio,name='portfolio'),
    path('blog/', include('blog.urls')),
    path('register/',user_views.register,name="register"),
    path('login/',authentication_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',authentication_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('messages/',include('contact.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    date = models.DateField()

    def __str__(self):
        return self.title

contact/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Contactclass(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    subject = models.CharField(max_length=80)
    message = models.TextField()

    def __str__(self):
        return str(self.user) + ': ' + str(self.subject)

portfolio/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Project(models.Model):
    user_name = models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

users/models.py
from django.db import models

# Create your models here.

contact/forms.py
from django import forms
from .models import Contactclass
from django.forms import  TextInput , Textarea
class contactform(forms.ModelForm):
    class Meta:
        model = Contactclass
        fields = ['subject','message']
        widgets = {
            'subject': TextInput(attrs={
                'class': "form-control",
                
                'placeholder': ' subject '
                }),
                'message': Textarea(attrs={
                'class': "form-control", 
                
                'placeholder': ' write your message here... '
                })
        }

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.forms import fields, models

class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=False)
    class meta:
        model = User
        fields = ['username','email','password1','password2']

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

def all_blogs(request):
    blogs = Blog.objects.order_by('-date')
    return render(request, 'blog/all_blogs.html', {'blogs':blogs})

def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html',{'blog':blog})

contact/views.py
from typing import ItemsView
from django.http import request
from django.shortcuts import render,get_object_or_404,redirect
from .models import Contactclass
from django.contrib.auth.decorators import login_required
from .forms import contactform
from django.views.generic.edit import CreateView



# Create your views here.
@login_required
def messages(request):
    all_objects = Contactclass.objects.all()[::-1]
    return render(request, 'contact/allmessage.html',{'objects':all_objects})

@login_required
def messagedetail(request, message_id):
    message = get_object_or_404(Contactclass, pk=message_id)
    return render(request, 'contact/detailmessage.html',{'object':message})

@login_required
def delete_message(request,id):
    message = Contactclass.objects.get(id=id)
    if request.method == 'POST' :
        message.delete()
        return redirect('contact:messages')
    return render(request,'contact/message-delete.html',{'item':message})

# old conctact me code
@login_required
def contactme(request):

    if request.method == 'POST':

        form = contactform(request.POST)

        if form.is_valid():
            form.instance.user = request.user
            form.save()
            return redirect('home')
    else:
         form = contactform()
    return render(request,'contact/contactme.html',{'form':form})

# class Contactme(CreateView):
#     model = Contactclass
#     fields = ['subject','message']
#     template_name = 'contact/contactme.html'
    
#     def form_valid(self, form):
#         form.instance.user = self.request.user
#         return super().form_valid(form)

portfolio/views.py
from django.shortcuts import render
from .models import Project
# Create your views here.

def home(request):
    # projects = Project.objects.all()
    return render(request,'portfolio/home.html')


def portfolio(request):
    projects = Project.objects.all()
    return render(request,'portfolio/folio.html',{'projects':projects})

users/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from .forms import RegisterForm
from django.contrib.auth.decorators import login_required
# Create your views here.
def register(request):
    
    
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,'welcome {0}. your account successfully created'.format(username))
            return redirect('login')
    else:
        form = RegisterForm()
    return render(request,'users/register.html',{'form' : form })

blog/templates/blog/all_blogs.html
{% extends "portfolio/base.html" %}

{% load static %}

{% block content %}
<br>
<div class='container'>
<div class="position-relative d-flex text-center mb-5">
        <h2 class="text-24 text-light opacity-4 text-uppercase fw-600 w-100 mb-0">Blogs</h2>
        <p class="text-9 text-dark fw-600 position-absolute w-100 align-self-center lh-base mb-0">Majid Fazel has written {{ blogs.count }} blog{{ blogs.count|pluralize }}<span class="heading-separator-line border-bottom border-3 border-primary d-block mx-auto"></span> </p>
      </div>




{% for blog in blogs %}
<div class="row justify-content-center my-3">
  <div class="col-md-10">
    <a href="{% url 'blog:detail' blog.id %}">
      <h2>{{ blog.title }}</h2>
    </a>
    <h5 class="text-muted">{{ blog.date|date:'M d Y'|upper }}</h5>
    <h4>{{ blog.description|striptags|truncatechars:100 }}</h4>
  </div>
</div>
<br>
{% endfor %}
</div>
<br><br><br><br>

{% endblock %}

blog/templates/blog/detail.html
{% extends "portfolio/base.html" %}
{% block content %}

<br>
<div class='container'>
        <h1 class="text-center " id="blogdetailtitle">{{ blog.title }}</h1>

        <h5 class="text-center text-muted mb-5">{{ blog.date|date:'F jS Y' }}</h5>

        {{ blog.description|safe }}
   </div>     
    
    <br><br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock %}

contact/templates/contact/allmessage.html
{% extends 'portfolio/base.html' %}

{% block content %}
<br>
<div class="container">
<h1 class="font-weight-bold text-center"><i class="bi bi-envelope-fill"></i> Messages</h1>

<h3 class="text-center mb-5">You have {{ objects.count }} message{{ objects.count|pluralize }}</h3>

{% for object in objects %}
<div class="row justify-content-center my-3">
  <div class="col-md-10">
    <a href="{% url 'contact:messagedetail' object.id %}">
      <h2> {{ object.user }}: {{ object.subject }}</h2>
    </a>
    <h5 class="text-muted">{{ blog.date|date:'M d Y'|upper }}</h5>
    <h4>{{ object.message|striptags|truncatechars:100 }}</h4>
  </div>
</div>
{% endfor %}
</div>
{% endblock %}

contact/templates/contact/contactme.html
{% extends 'portfolio/base.html' %}

{% block content %}
   <!-- Contact Me
    ============================================= -->
    <section id="contact" class="section bg-light">
    <form method="POST">
        {% csrf_token %}
    
      <div class="container px-lg-5">
        <!-- Heading -->
        <div class="position-relative d-flex text-center mb-5">
          <h2 class="text-24 text-light opacity-4 text-uppercase fw-600 w-100 mb-0">Contact</h2>
          <p class="text-9 text-dark fw-600 position-absolute w-100 align-self-center lh-base mb-0">Get in Touch<span class="heading-separator-line border-bottom border-3 border-primary d-block mx-auto"></span> </p>
        </div>
        <!-- Heading end-->
        <div class="row gy-5">
          <div class="col-md-4 col-xl-3 order-1 order-md-0 text-center text-md-start">
            <h2 class="mb-3 text-5 text-uppercase">Address</h2>
            <p class="text-3 mb-4">Tehran , iran<br>
           </p>
            <p class="text-3 mb-1"><span class="text-primary text-4 me-2"><i class="fas fa-phone"></i></span>(+98) 9128026963</p>
            <p class="text-3 mb-1"><span class="text-primary text-4 me-2"><i class="fas fa-fax"></i></span>(+98) 9378990958 </p>
            <p class="text-3 mb-4"><span class="text-primary text-4 me-2"><i class="fas fa-envelope"></i></span>seyedmajidfazel@gmail.com</p>
            
          </div>
          <div class="col-md-8 col-xl-9 order-0 order-md-1">
            <h2 class="mb-3 text-5 text-uppercase text-center text-md-start">Send me a message</h2>
			

			  <div class="row g-4">
                <div class="col-xl-6">
                  {{ form.subject }}
                    
                </div>
                <div class="col-xl-6">
                 
                    <br>
                </div>
				<div class="col">
          {{ form.message }}
					
				</div>
              </div>

              <p class="text-center mt-4 mb-0">
				<button id="submit-btn" class="btn btn-primary rounded-pill d-inline-flex" type="submit">Send Message</button>
              </p>
            
          </div>
        </div>
      </div>
    </form>
    </section>
    <!-- Contact Me end -->
{% endblock %}

contact/templates/contact/detailmessage.html
{% extends "portfolio/base.html" %}

{% load static %}

{% block content %}

<br>
<div class="container">


<h1> message from: {{ object.user }}</h1>
<div class="card">
    <div class="card-title">
        <h1 class="text-center mt-5" >{{ object.subject }}</h1>
    </div>
    <div class="card-body">
        {{ object.message|safe }}
    </div>
</div>
<br>
<a href="{% url 'contact:delete_message' object.id %}" class="btn btn-danger">Delete</a>

<br><br><br><br><br><br><br>
</div>
{% endblock %}

contact/templates/contact/message-delete.html
{% extends 'portfolio/base.html' %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    <h1>are you sure you want to delete {{ item.subject }} ?</h1>
    
    <button type="submit" class="btn btn-danger">submit</button>
   
</form>
<br>
<a href="{% url 'contact:messages' %}" class="btn btn-info">cancell</a>



<br><br><br><br><br><br>
{% endblock %}

portfolio/templates/portfolio/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="images/favicon.png" rel="icon" />
<title>Majid Fazel </title>
<meta name="description" content="Simone is responsive bootstrap 5 one page personal portfolio html template.">
<meta name="author" content="harnishdesign.net">



<link rel="icon" type="image/png" href="{% static "portfolio/Logo.png" %}">


<!-- Web Fonts -->
<link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

<!-- Stylesheet
============================== -->
<!-- Bootstrap -->
<link rel="stylesheet" type="text/css" href="{% static "portfolio/vendor/bootstrap/css/bootstrap.min.css" %}" />
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<!-- Font boostrap Icon -->
 <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
<!-- Owl Carousel -->
<link rel="stylesheet" type="text/css" href="{% static "portfolio/vendor/owl.carousel/assets/owl.carousel.min.css" %}" />
<!-- Magnific Popup -->
<link rel="stylesheet" type="text/css" href="{% static "portfolio/vendor/magnific-popup/magnific-popup.min.css" %}" />
<!-- Custom Stylesheet -->
<link rel="stylesheet" type="text/css" href="{% static "portfolio/css/stylesheet.css" %}" />
<!-- Colors Css -->


<style>
  ::-webkit-scrollbar{
    width: 10px;
  }

  ::-webkit-scrollbar-track{
    background:#a8a8a8;
    border-radius: 50px;;
  }

  ::-webkit-scrollbar-thumb{
    background: #1BAA80;
    border-radius: 50px;
  }


</style>


</head>

<body class="side-header" data-bs-spy="scroll" data-bs-target="#header-nav" data-bs-offset="1">

<!-- Preloader -->
 <div class="preloader">
  <div class="lds-ellipsis">
    <div></div>
    <div></div>
    <div></div>
    <div></div>
  </div>
</div> 
<!-- Preloader End -->

<!-- Document Wrapper
=============================== -->
<div id="main-wrapper">
  <!-- Header
  ============================ -->
  <header id="header" class="sticky-top">
    <!-- Navbar -->
    <nav class="primary-menu navbar navbar-expand-lg bg-dark navbar-text-light border-bottom-0">
      <div class="container-fluid position-relative h-100 flex-lg-column ps-3 px-lg-3 pt-lg-3 pb-lg-2">

        <!-- Logo -->
        <a href="{% url 'home' %}" class="mb-lg-auto mt-lg-4">
			<span class="bg-dark-2 rounded-pill p-2 mb-lg-1 d-none d-lg-inline-block">
				<img class="img-fluid rounded-pill d-block" src="{% static "portfolio/majid-logo.jpg" %}" title="I'm Simone" alt="">
			</span>
			<h1 class="text-5 text-white text-center mb-0 d-lg-block">Majid Fazel</h1>
        </a>
        <!-- Logo End -->

        <div id="header-nav" class="collapse navbar-collapse w-100 my-lg-auto">
          <ul class="navbar-nav text-lg-center my-lg-auto py-lg-3">
            <li class="nav-item"><a class="nav-link active" href="{% url 'home' %}">Home</a></li>
    
            <li class="nav-item"><a class="nav-link" href="{% url 'portfolio' %}">Portfolio</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'blog:all_blogs' %}">Blogs</a></li>

            {% if perms.user.super %}
          <li>
            <a role="button" href="{% url 'contact:messages' %}" class="nav-link"><i class="bi bi-bell-fill"></i> messages</a>
          </li>
          <li>
            <a role="button" href="{% url 'admin:index' %}" class="nav-link"><i class="bi bi-person-circle"></i> Admin panel</a>
          </li>
          {% else %}
          <li>
            <a role="button" href="{% url 'contact:contactme' %}" class="nav-link"> contact </a>
          </li>
         {% endif %}
          {% if user.is_authenticated %}
          
          <li class="nav-link"><i class="bi bi-person-fill" style='color:green'></i> {{ user.username }}</li>
          <li>
            <a role="button" href="{% url 'logout' %}"><i class="bi bi-box-arrow-left"></i> Logout</a>
          </li>
         
          {% else %}
          <li>
            <a role="button" href="{% url 'login' %}" class="nav-link" ><i class="bi bi-box-arrow-right"></i> Login</a>
            
          </li>
          <li>
            <a role="button" href="{% url 'register' %}" class="nav-link">Register</a>
          </li>
          {% endif %}
          </ul>
        </div>
        <ul class="social-icons social-icons-muted social-icons-sm mt-lg-auto ms-auto ms-lg-0 d-flex">
          
          <li class="social-icons-facebook"><a data-bs-toggle="tooltip" title="Telegram" href="https://t.me/majidfazel" target="_blank"><i class="bi bi-telegram"></i></a></li>
          <li class="social-icons-twitter"><a data-bs-toggle="tooltip" title="Twitter" href="https://twitter.com/majidfazel83" target="_blank"><i class="bi bi-twitter"></i></a></li>
          <li class="social-icons-facebook"><a data-bs-toggle="tooltip" title="Email" href="mailto:seyedmajidfazel@gmail.com" target="_blank"><i class="bi bi-envelope-fill"></i></a></li>
          <li class="social-icons-dribbble"><a data-bs-toggle="tooltip" title="Instagram" data-bs-placement="top" href="https://www.instagram.com/seyedmajidfazel/" target="_blank"><i class="bi bi-instagram"></i></a></li>
          <li class="social-icons-twitter"><a data-bs-toggle="tooltip" title="Linkdin" data-bs-placement="top" href="https://www.linkedin.com/in/majid-fazel-522635168/" target="_blank" ><i class="bi bi-linkedin"></i></a></li>
          
        </ul>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#header-nav"><span></span><span></span><span></span></button>
      </div>
    </nav>
    <!-- Navbar End -->
  </header>
  <!-- Header End -->


  

  <!-- Content
  ============================================= -->
  <div id="content" role="main">


     {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">
            {{ message }}
          </div>

        {% endfor %}
      {% endif %}


    {% block content %}{% endblock %}

   


  </div>
  <!-- Content end -->

  <!-- Footer
  ============================================= -->
  <footer id="footer" class="section">
    <div class="container px-lg-5">
      <div class="row">
        <div class="col-lg-6 text-center text-lg-start">
          <p class="mb-3 mb-lg-0">Copyright © Majid fazel 2021 . All Rights Reserved.</p>
        </div>
       
      </div>
    </div>
  </footer>
  <!-- Footer end -->

</div>
<!-- Document Wrapper end -->

<!-- Back to Top
============================================= -->
<a id="back-to-top" class="rounded-circle" data-bs-toggle="tooltip" title="Back to Top" href="javascript:void(0)"><i class="bi bi-arrow-up-circle"></i></a>





<!-- JavaScript -->
<script src="{% static "portfolio/vendor/jquery/jquery.min.js" %}"></script>
<script src="{% static "portfolio/vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
<!-- Easing -->
<script src="{% static "portfolio/vendor/jquery.easing/jquery.easing.min.js" %}"></script>
<!-- Appear -->
<script src="{% static "portfolio/vendor/jquery.appear/jquery.appear.min.js" %}"></script>
<!-- Images Loaded -->
<script src="{% static "portfolio/vendor/imagesloaded/imagesloaded.pkgd.min.js" %}"></script>
<!-- Counter -->
<script src="{% static "portfolio/vendor/jquery.countTo/jquery.countTo.min.js" %}"></script>
<!-- Parallax Bg -->
<script src="{% static "portfolio/vendor/parallaxie/parallaxie.min.js" %}"></script>
<!-- Typed -->
<script src="{% static "portfolio/vendor/typed/typed.min.js" %}"></script>
<!-- Owl Carousel -->
<script src="{% static "portfolio/vendor/owl.carousel/owl.carousel.min.js" %}"></script>
<!-- isotope Portfolio Filter -->
<script src="{% static "portfolio/vendor/isotope/isotope.pkgd.min.js" %}"></script>
<!-- Magnific Popup -->
<script src="{% static "portfolio/vendor/magnific-popup/jquery.magnific-popup.min.js" %}"></script>

<!-- Custom Script -->
<script src="{% static "portfolio/js/theme.js" %}"></script>
</body>
</html>

portfolio/templates/portfolio/folio.html
{% extends 'portfolio/base.html' %}
{% block content %}
<br>
<div class="container">
    <div class="position-relative d-flex text-center mb-5">
        <h2 class="text-24 text-light opacity-4 text-uppercase fw-600 w-100 mb-0">Portfolio</h2>
        <p class="text-9 text-dark fw-600 position-absolute w-100 align-self-center lh-base mb-0">My Work & learning<span class="heading-separator-line border-bottom border-3 border-primary d-block mx-auto"></span> </p>
      </div>
      <br>
    <div class="row">
            {% for project in projects %}
            
            <div class="col-md-4 d-flex justify-content-center">
                <div class="card" style="width: 20rem;">
                    
                    <img class="card-img-top" src="{{ project.image.url }}" alt="project image">
                    <div class="card-body">
                    <h5 class="card-title"> {{ project.title }} </h5>
                    <p class="card-text"> {{ project.description }} </p>
                    
                    </div>
                </div>
                
            </div>
              
                {% endfor %}
               
        </div>


</div>
<br><br><br>
{% endblock %}

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}
{% block content %}


{% load static %}

<!-- Intro
    ============================================= -->
    <section id="home">
      <div class="hero-wrap">
        <div class="hero-mask opacity-8 bg-dark"></div>
        <div class="hero-bg parallax" style="background-image:url('{% static "portfolio/mainback.jpeg" %}');"></div>
        <div class="hero-content section d-flex fullscreen">
          <div class="container my-auto">
            <div class="row">
              <div class="col-12 text-center">
                <div class="typed-strings">
                  <p>I'm Majid Fazel</p>
                  <p>I'm a Backend Developer.</p>
                  <p>i started learing programmin since 2017</p>
                  <p>I'm doing my best 😊</p>
                </div>
                <p class="text-7 fw-500 text-white mb-2 mb-md-3">Welcome</p>
                <h2 class="text-16 fw-600 text-white mb-2 mb-md-3"><span class="typed"></span></h2>
                <p class="text-5 text-light mb-4">curently in Tehran, Iran.</p>
			
                <a role="button" href="{% url 'contact:contactme' %}" class="btn btn-outline-primary rounded-pill shadow-none mt-2">Contact Me</a>
              </div>
            </div>
          </div>
          <a href="#about" class="scroll-down-arrow text-white smooth-scroll"><span class="animated"><i class="fa fa-chevron-down"></i></span></a> </div>
      </div>
    </section>
    <!-- Intro end -->

    <!-- About
    ============================================= -->
    <section id="about" class="section">
      <div class="container px-lg-5">
        <!-- Heading -->
        <div class="position-relative d-flex text-center mb-5">
          <h2 class="text-24 text-light opacity-4 text-uppercase fw-600 w-100 mb-0">About Me</h2>
          <p class="text-9 text-dark fw-600 position-absolute w-100 align-self-center lh-base mb-0">Know Me More<span class="heading-separator-line border-bottom border-3 border-primary d-block mx-auto"></span> </p>
        </div>
        <!-- Heading end-->

        <div class="row gy-5">
          <div class="col-lg-7 col-xl-8 text-center text-lg-start">
            <h2 class="text-7 fw-600 mb-3">I'm <span class="text-primary">Majid Fazel</span></h2>
            <p> i'm a backend Dev learning python and data Science </p>
            <p> i can help you build your own websites and projects </p>
          </div>
          <div class="col-lg-5 col-xl-4">
            <div class="ps-lg-4">
              <ul class="list-style-2">
                <li class=""><span class="fw-600 me-2">Name:</span>Majid fazel</li>
                <li class=""><span class="fw-600 me-2">Email:</span><a href="seyedmajidfazel@gmail.com">seyedmajidfazel@gmail.com</a></li>
                <li class=""><span class="fw-600 me-2">Born:</span>2004</li>
                <li class="border-0"><span class="fw-600 me-2">From:</span>Tehran, iran</li>
              </ul>
              <a href="{% static "portfolio/resume.pdf" %}" class="btn btn-primary rounded-pill"><i class="bi bi-cloud-arrow-down-fill"></i> Download CV</a> </div>
          </div>
        </div>
        <div class="brands-grid separator-border mt-5">
          <div class="row">
            <div class="col-6 col-md-3">
              <div class="featured-box text-center">
                <h4 class="text-12 text-muted mb-0"><span class="counter" data-from="0" data-to="3">3</span>+</h4>
                <p class="mb-0">Years Experiance</p>
              </div>
            </div>
            <div class="col-6 col-md-3">
              <div class="featured-box text-center">
                <h4 class="text-12 text-muted mb-0"><span class="counter" data-from="0" data-to="15">15</span>+</h4>
                <p class="mb-0">Happy Clients</p>
              </div>
            </div>
            <div class="col-6 col-md-3">
              <div class="featured-box text-center">
                <h4 class="text-12 text-muted mb-0"><span class="counter" data-from="0" data-to="25">25</span>+</h4>
                <p class="mb-0">Projects Done</p>
              </div>
            </div>
            <div class="col-6 col-md-3">
              <div class="featured-box text-center">
                <h4 class="text-12 text-muted mb-0"><span class="counter" data-from="0" data-to="2">2</span></h4>
                <p class="mb-0">Get Awards</p>
              </div>
            </div>
          </div>
        </div>

      	<h2 class="text-6 fw-600 mt-4 mb-4">My Skills</h2>
        <div class="row gx-5">
          <div class="col-md-6">
            <p class="text-dark fw-500 text-start mb-2">Web Design <span class="float-end">65%</span></p>
            <div class="progress progress-sm mb-4">
              <div class="progress-bar" role="progressbar" style="width: 65%" aria-valuenow="65" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
            <p class="text-dark fw-500 text-start mb-2">HTML/CSS <span class="float-end">95%</span></p>
            <div class="progress progress-sm mb-4">
              <div class="progress-bar" role="progressbar" style="width: 95%" aria-valuenow="95" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
            
          </div>
          <div class="col-md-6">
            <p class="text-dark fw-500 text-start mb-2">python <span class="float-end">70%</span></p>
            <div class="progress progress-sm mb-4">
              <div class="progress-bar" role="progressbar" style="width: 70%" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
            
            <p class="text-dark fw-500 text-start mb-2">Bootstrap <span class="float-end">98%</span></p>
            <div class="progress progress-sm mb-4">
              <div class="progress-bar" role="progressbar" style="width: 98%" aria-valuenow="98" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
          </div>
        </div>



      </div>
      
    </section>
    <!-- About end -->



    
{% endblock %}

users/templates/users/logout.html
{% extends 'portfolio/base.html' %}

{% block content %}
<br><br><br>
<div class="container">
  <div class="row">
    
  
    <div class="card col-md-8 offset-md-2">
        <h5 class="card-header"><i class="bi bi-info-circle" style="color: cornflowerblue;"></i></h5>
        <div class="card-body">
          <h5 class="card-title">You are logged out</h5>
          <p class="card-text">you are succesfully logged out of website.</p>
          <a href="{% url 'home' %}" class="btn btn-primary">Home</a>
          <a href="{% url 'login' %}" class="btn btn-info">Login</a>
        </div>
      </div>
</div>
</div>
<br><br><br><br><br><br><br><br>
{% endblock %}